### ISSUE TITLE
Revenge doesn't work in discord versions 221 and above

### ISSUE THREAD

**Issue by Czekoloczek** [revenge-mod/Revenge#35]
When you try to open discord on the latest alpha it's stuck on the loading discord icon

**Comment by MasterCraft6969** [comment]
Same issue

**Comment by ProfessorSparrs** [comment]
same here :(

**Comment by UnforseenDeath** [comment]
Hey I found a way to fix it! 
You need to tap the version button 10 times in the installer in the about section 

After that you'll get dev settings and you need to change the download path to 

/storage/emulated/0/Download/app-release.apk

**Comment by naloder** [comment]
same here 
try to reinstall and still not wrok

**Comment by m41denx** [comment]
Same.
Looks like it occurs with Discord 221+ (All channels).

This issue is most likely present in the vendetta xposed module itself rather than revenge-specific things, as default vendetta build w/o revenge doesn't work as well (expected to boot with no issues and at least crash in react runtime)

I found a temporary solution: downgrading to 220.18 (dev settings → version 220018). If you don't want to lose  installed plugins - change package name in dev settings too to install fresh app alongside old one, you will be able to switch back when issue is resolved

**Comment by UnforseenDeath** [comment]
If you look in the discord for revenge people have already posted permanent fixes to it.

**Comment by m41denx** [comment]
> If you look in the discord for revenge people have already posted permanent fixes to it.

I wouldn't post here if simple "download new xposed module" worked. Also I had revenge's jsdelivr url in vendetta since they announced project archival. And if you propose "just reinstall" method - as I've stated before - I already installed v220 as a second app

**Comment by tmprnc** [comment]
> If you look in the discord for revenge people have already posted permanent fixes to it.

Do you have a link to this Discord? It's not linked anywhere on Github.

**Comment by Ushie** [comment]
https://discord.com/invite/ddcQf3s2Uq

**Comment by UnforseenDeath** [comment]
> > If you look in the discord for revenge people have already posted permanent fixes to it.
> 
> I wouldn't post here if simple "download new xposed module" worked. Also I had revenge's jsdelivr url in vendetta since they announced project archival. And if you propose "just reinstall" method - as I've stated before - I already installed v220 as a second app

I'm saying you need to change the place where the application is Installed to and it will work fine. I'm on the newest version and after changing the directory for the application it worked fine
